//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParcelMoving
    {
        public int id { get; set; }
        public bool readingPZ { get; set; }
        public bool readingWZ { get; set; }
        public int idParcel { get; set; }
        public int idDoc { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual Parcel Parcel { get; set; }
    }
}
